sonar.projectKey=homeassistant-acinfinity
sonar.projectName=homeassistant-acinfinity
sonar.organization=dalinicus
sonar.sources=custom_components
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**,config/**,.venv/**
sonar.sourceEncoding=UTF-8